Repository Boavizta/cloud-scanner, pull requests merged in 2024-11, with the labels that each got.

#610 chore: update to Rust 1.82
  CHANGELOG.md
  Dockerfile
Labels: dependencies

#617 docker-compose: use 'default' profile by default
  CHANGELOG.md
  docker-compose.yml
Labels: enhancement

#619 Apply filters for 'Primary Energy (Use) for 1 hour', fixes #618
  CHANGELOG.md
  dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
Labels: bug, grafana
