Repository Boavizta/cloud-scanner, pull requests merged in 2024-12, with the labels that each got.

#623 Lack of available impact data from the API crashes the scanner #622
  CHANGELOG.md
  cloud-scanner-cli/src/metric_exporter.rs
Labels: bug

#626 bug(dockerfile): Build only the CLI dependencies with the Dockerfile …
  Dockerfile
Labels: enhancement

#630 Minor dashboard improvements and facilitate access to it
  CHANGELOG.md
  dashboard-config/provisioning/dashboards/grafana-dashboard-cloud-impacts.template.json
  docker-compose.yml
Labels: enhancement

#631 Mark next version post release with -SNAPSHOT, fixes #624
  CHANGELOG.md
  cloud-scanner-cli/Cargo.toml
  cloud-scanner-lambda/Cargo.toml
Labels: enhancement

#646 Upgrade version of BoaviztAPI to 1.3.7 and adjust tests accordingly.
  CHANGELOG.md
  cloud-scanner-cli/src/boavizta_api_v1.rs
  cloud-scanner-cli/test-data/DEFAULT_RAW_IMPACTS_OF_M6GXLARGE_1HRS_FR.json
  docker-compose.yml
Labels: bug

#642 more recent versions of dashboard
  docs/src/images/cloud-scanner-dashboard-clear.png
  docs/src/images/cloud-scanner-dashboard-dark.png
  docs/src/tutorials/quickstart-dashboard-docker.md
Labels: documentation

#647 feat: Return API and scanner version in the metrics output.
  CHANGELOG.md
  cloud-scanner-cli/src/metric_exporter.rs
Labels: enhancement

#650 added description, repo, keywords and license
  cloud-scanner-cli/Cargo.toml
Labels: enhancement
